# Generated by Django 4.2.4 on 2023-08-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_book_borrower_remove_borrowrequest_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Book Author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('C', 'COLLECTED'), ('C', 'COMPLETE'), ('D', 'DECLINED')], default='m', help_text='Book availability', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Select a genre for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre'),
        ),
    ]
