# Generated by Django 4.2.4 on 2023-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'PENDING'), ('2', 'APPROVED'), ('3', 'COLLECTED'), ('4', 'COMPLETE'), ('5', 'DECLINED')], default='m', help_text='Book availability', max_length=20),
        ),
    ]
