# Generated by Django 4.2.4 on 2023-09-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_language_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'ordering': ['due_date'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
